### ISSUE TITLE
Installation Problems with R/setupRTorsten.R

### ISSUE THREAD

**Issue by areeye** [metrumresearchgroup/example-models#9]
I am having troubles installing torsten. 

I have installed rstan 2.16.2 successfully. 

during the installation the code wants to change directory to ~/lib and that directory does not seem to exist. 

Any suggestions? Thanks
Areeye

[installation_Error_112217.txt](https://github.com/metrumresearchgroup/example-models/files/1497408/installation_Error_112217.txt)

**Comment by billgillespie** [comment]
Hi Areeye,

We recently posted a new method for installing rstan with the Torsten functions. See https://github.com/metrumresearchgroup/TorstenHeaders. It simplifies the installation process.

I see I need to revise example-models README to reflect this change.

Thanks,
Bill

**Comment by charlesm93** [comment]
You could edit the script `setupRTorsten.R`  to specify the filepath for `lib` -- but the new method seems like the way to go.

**Comment by billgillespie** [comment]
setupRTorsten.R is now replaced by the R package TorstenHeaders (https://github.com/metrumresearchgroup/TorstenHeaders). This will be documented in Torsten version 0.84.
